<?php

namespace Jmurphy\LaravelOkta\Tests;

use Illuminate\Http\Client\Factory;
use Illuminate\Support\Facades\Http;
use Jmurphy\LaravelOkta\Okta\ClientAdapter;
use PHPUnit\Framework\TestCase;

class ClientTest extends TestCase
{
    /**
     * @var ClientAdapter
     */
    private $httpClient;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->httpClient = new ClientAdapter(new Factory);
    }

    public function testAddAuthorizationHeader()
    {
        $this->httpClient->addAuthorizationHeader('TOKEN_TEST');
        $this->assertArrayHasKey('Authorization',$this->httpClient->getHeaders());
        $this->assertEquals('SSWS TOKEN_TEST',$this->httpClient->getHeaders()['Authorization']);
    }

    public function testGet()
    {
        $this->assertTrue(true);
    }

    public function testAddHeaders()
    {
        $this->httpClient->addHeaders(['ContentType' => '']);
        $this->httpClient->addHeaders(['TestHeader' => '']);
        $this->assertArrayHasKey('ContentType',$this->httpClient->getHeaders());
        $this->assertArrayHasKey('TestHeader',$this->httpClient->getHeaders());
    }
}
